---
title: People
format: html
---

The Chase Native Bees Lab is committed to supporting a diverse and inclusive community of scientists from all backgrounds, identities, and career stages. We aim to foster an inclusive and respectful workplace by prioritizing open communication, building supportive relationships, partaking in trainings and workshops, and expanding participation in entomology, the broader biological sciences, and academia.

## Principal Investigator

-   **Marissa Chase** — Assistant Professor, Department of Biology, Villanova University

    -   Marissa (she/her) teaches courses in entomology and evolutionary ecology. While her research encompasses all things related to wild bee biology and ecology, with an emphasis on bee population dynamics, nesting, and restoration, she is a bug nerd and lover of all insects. Aside from entomology-related fun, Marissa will happily pet your dog and go on a hike to forage mushrooms or track down a historical rare plant record.

        -   Post-doc — University of Minnesota (adviser: Dan Cariveau)

        -   PhD — University of Illinois (co-advisers: Alex Harmon-Threatt and Jen Fraterrigo)

        -   BS — UC Berkeley

## Graduate students

-   

## Undergraduate students

-   

## Staff

-   **Ror** — Lab manager
    -   Ror is an exceptional herder, with years of experience herding his mom to lab and making her finish writing her papers. His lab responsibilities include: reminding you to go outside and touch (native) grass and finishing that sandwich you were eating. In his free time, Ror loves long, meandering walks through dumpster-filled alleys, incidental seed dispersal while wading through prairies and muck, and creating bizarre sounds both day and night.
