---
title: Publications
format: html
---

## Peer-Reviewed Publications

### 2026

Chase, M.H., Portman, Z.M., Petersen, J.D., Gerjets, N., Kranz, R., LaBry, F., et al. The nesting biology and foraging distance of the bee *Colletes andrewsi* (Hymenoptera, Colletidae), a rare specialist of *Heuchera* spp. *Journal of Hymenoptera Research*, 99, 703–722. <https://doi.org/10.3897/jhr.99.189555>

Portman, Z.M., Bruninga-Socolar, B., Chase, M.H., Harrison, T., Arduser, M., et al. Ghost records and unverifiable specimen data hinder bee research: a reply to Cobb et al. *Annals of the Entomological Society of America*, 119(3), 79–82. <https://doi.org/10.1093/aesa/saag002>

Chase, M.H., Gerjets, N., Lane, I.G., Petersen, J.D., Portman, Z.M., & Cariveau, D.P. Soil sand content is a driving force in structuring bee communities. *Insect Conservation and Diversity*, 19(3), 675–685. <https://doi.org/10.1111/icad.70051>

### 2025

Zinnen, J., Chase, M.H., Charles, B., Harmon-Threatt, A., & Matthews, J.W. (2025). Pollinator seed mixes are phenologically dissimilar to prairie remnants. *Restoration Ecology*, 33(3), e14352. <https://doi.org/10.1111/rec.14352>

Portman, Z.M., Bruninga-Socolar, B., Chase, M.H., Harrison, T., Arduser, M., et al. (2025). Big data, changing taxonomy, and ghost records: permanent preservation of collected specimens is essential for insect monitoring. *Annals of the Entomological Society of America*, 118(4), 331–345. <https://doi.org/10.1093/aesa/saaf023>

Chase, M.H., Portman, Z.M., Lane, I.G., Herron-Sweet, C.R., & Cariveau, D.P. (2025). Pollinator plantings in the intensively farmed Midwest (USA) support a core set of common bee species, regardless of local and landscape controls. *Restoration Ecology*, 33(8), e70175. <https://doi.org/10.1111/rec.70175>

Zinnen, J., Chase, M.H., Charles, B., Meissen, J., & Matthews, J.W. (2025). RELIX: a dataset of vascular plant species presence for 353 prairie remnants in the Midwestern United States, with prairie remnant metadata. *Natural Areas Journal*, 45(3), 150–158. <https://doi.org/10.3375/2162-4399-45.3.3>

Chase, M.H., Harmon-Threatt, A., Stickley, S.F., Charles, B., & Fraterrigo, J.M. (2025). Evaluating LiDAR-derived structural metrics for predicting bee assemblages in managed forests. *Ecology and Evolution*, 15(4), e71159. <https://doi.org/10.1002/ece3.71159>

### 2023

Chase, M.H., Fraterrigo, J.M., & Harmon-Threatt, A. (2023). Bee functional traits and their relationship to pollination services depend on many factors: a meta-regression analysis. *Insect Conservation and Diversity*, 16(3), 313–323. <https://doi.org/10.1111/icad.12635>

Chase, M.H., Fraterrigo, J.M., Charles, B., & Harmon-Threatt, A. (2023). Wild bee response to forest management varies seasonally and is mediated by resource availability. *Forest Ecology and Management*, 548, 121426. <https://doi.org/10.1016/j.foreco.2023.121426>

Charles, B., Chase, M., Pociask, G., Bhattarai, R., & Matthews, J.W. (2023). Restored wetlands are greatly influenced by hydrology and non-native plant invasion. *Wetlands Ecology and Management*, 31(1), 129–142. <https://doi.org/10.1007/s11273-022-09905-0>

Chase, M.H., Charles, B., Harmon-Threatt, A., & Fraterrigo, J.M. (2023). Diverse forest management strategies support functionally and temporally distinct bee communities. *Journal of Applied Ecology*, 60(11), 2375–2388. <https://doi.org/10.1111/1365-2664.14513>

Chase, M.H., Frankie, G.W., Jadallah, C., Coville, R., Pawlek, J., Witt, S., & Thorp, R. (2023). Common bees in California gardens. University of California Division of Agriculture and Natural Resources Publishing.

Chase, M.H., Charles, B., Frankie, G.W., Coville, R., Pawelek, J., Witt, S. (2023). Common plants to attract California native bees. University of California Division of Agriculture and Natural Resources Publishing.

### 2022

Charles, B., Chase, M.H., Pociask, G., Bhattarai, R., & Matthews, J.W. (2022). Can functional leaf traits be used for monitoring wetland restoration? A comparison between commonly used monitoring metrics and functional leaf traits. *Ecological Indicators*, 140, 109032. <https://doi.org/10.1016/j.ecolind.2022.109032>

### 2019

Guzman, A., Chase, M., & Kremen, C. (2019). On-farm diversification in an agriculturally-dominated landscape positively influences specialist pollinators. *Frontiers in Sustainable Food Systems*, 3, 87. <https://doi.org/10.3389/fsufs.2019.00087>

Frankie, G., Feng, I., Thorp, R., Pawelek, J., Chase, M.H., & Jadallah, C.C. (2019). Native and non-native plants attract diverse bees to urban gardens in California. *Journal of Pollination Ecology*, 25. <https://doi.org/10.26786/1920-7603(2019)505>

### 2018

Frankie, G.W., Pawelek, J.C., Guerrero, S.S.L., Thorp, R.W., Rizzardi, M.A., et al. (2018). Survey of native and honey bees from agricultural Brentwood and their constructed bee gardens in Northern California, 2010–2018. *Journal of the Kansas Entomological Society*, 91(4), 310–349.

Frankie, G., Pawelek, J., Chase, M., Witt, S., & Faber, B. (2018). Native pollinators of avocado as affected by constructed pollinator habitat gardens in southern California. *XXX International Horticultural Congress IHC2018: VII International...*
